# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ots/player_risk_score.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ots/player_risk_score.proto',
  package='ots',
  syntax='proto3',
  serialized_options=b'\n\rcom.oddin.otsZ\014oddin.gg/ots',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1bots/player_risk_score.proto\x12\x03ots\"$\n\x16PlayerRiskScoreRequest\x12\n\n\x02id\x18\x01 \x01(\t\"(\n\x17PlayerRiskScoreResponse\x12\r\n\x05score\x18\x01 \x01(\x02\x42\x1d\n\rcom.oddin.otsZ\x0coddin.gg/otsb\x06proto3'
)




_PLAYERRISKSCOREREQUEST = _descriptor.Descriptor(
  name='PlayerRiskScoreRequest',
  full_name='ots.PlayerRiskScoreRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ots.PlayerRiskScoreRequest.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=72,
)


_PLAYERRISKSCORERESPONSE = _descriptor.Descriptor(
  name='PlayerRiskScoreResponse',
  full_name='ots.PlayerRiskScoreResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='score', full_name='ots.PlayerRiskScoreResponse.score', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=114,
)

DESCRIPTOR.message_types_by_name['PlayerRiskScoreRequest'] = _PLAYERRISKSCOREREQUEST
DESCRIPTOR.message_types_by_name['PlayerRiskScoreResponse'] = _PLAYERRISKSCORERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PlayerRiskScoreRequest = _reflection.GeneratedProtocolMessageType('PlayerRiskScoreRequest', (_message.Message,), {
  'DESCRIPTOR' : _PLAYERRISKSCOREREQUEST,
  '__module__' : 'ots.player_risk_score_pb2'
  # @@protoc_insertion_point(class_scope:ots.PlayerRiskScoreRequest)
  })
_sym_db.RegisterMessage(PlayerRiskScoreRequest)

PlayerRiskScoreResponse = _reflection.GeneratedProtocolMessageType('PlayerRiskScoreResponse', (_message.Message,), {
  'DESCRIPTOR' : _PLAYERRISKSCORERESPONSE,
  '__module__' : 'ots.player_risk_score_pb2'
  # @@protoc_insertion_point(class_scope:ots.PlayerRiskScoreResponse)
  })
_sym_db.RegisterMessage(PlayerRiskScoreResponse)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
