# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ots/resolve_foreign_events_in_ticket.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from ots_schema.ots.enum import enums_pb2 as ots_dot_enum_dot_enums__pb2
from ots_schema.ots import commons_pb2 as ots_dot_commons__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ots/resolve_foreign_events_in_ticket.proto',
  package='ots',
  syntax='proto3',
  serialized_options=b'\n\rcom.oddin.otsZ\014oddin.gg/ots',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n*ots/resolve_foreign_events_in_ticket.proto\x12\x03ots\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x14ots/enum/enums.proto\x1a\x11ots/commons.proto\"w\n#ResolveForeignEventsInTicketRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x15\n\rforeign_stake\x18\x03 \x01(\x04\x12-\n\ttimestamp\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"p\n$ResolveForeignEventsInTicketResponse\x12+\n\x06status\x18\x01 \x01(\x0e\x32\x1b.ots.enums.AcceptanceStatus\x12\x1b\n\x06reason\x18\x02 \x01(\x0b\x32\x0b.ots.ReasonB\x1d\n\rcom.oddin.otsZ\x0coddin.gg/otsb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,ots_dot_enum_dot_enums__pb2.DESCRIPTOR,ots_dot_commons__pb2.DESCRIPTOR,])




_RESOLVEFOREIGNEVENTSINTICKETREQUEST = _descriptor.Descriptor(
  name='ResolveForeignEventsInTicketRequest',
  full_name='ots.ResolveForeignEventsInTicketRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ots.ResolveForeignEventsInTicketRequest.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='foreign_stake', full_name='ots.ResolveForeignEventsInTicketRequest.foreign_stake', index=1,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='ots.ResolveForeignEventsInTicketRequest.timestamp', index=2,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=125,
  serialized_end=244,
)


_RESOLVEFOREIGNEVENTSINTICKETRESPONSE = _descriptor.Descriptor(
  name='ResolveForeignEventsInTicketResponse',
  full_name='ots.ResolveForeignEventsInTicketResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='ots.ResolveForeignEventsInTicketResponse.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='reason', full_name='ots.ResolveForeignEventsInTicketResponse.reason', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=246,
  serialized_end=358,
)

_RESOLVEFOREIGNEVENTSINTICKETREQUEST.fields_by_name['timestamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_RESOLVEFOREIGNEVENTSINTICKETRESPONSE.fields_by_name['status'].enum_type = ots_dot_enum_dot_enums__pb2._ACCEPTANCESTATUS
_RESOLVEFOREIGNEVENTSINTICKETRESPONSE.fields_by_name['reason'].message_type = ots_dot_commons__pb2._REASON
DESCRIPTOR.message_types_by_name['ResolveForeignEventsInTicketRequest'] = _RESOLVEFOREIGNEVENTSINTICKETREQUEST
DESCRIPTOR.message_types_by_name['ResolveForeignEventsInTicketResponse'] = _RESOLVEFOREIGNEVENTSINTICKETRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ResolveForeignEventsInTicketRequest = _reflection.GeneratedProtocolMessageType('ResolveForeignEventsInTicketRequest', (_message.Message,), {
  'DESCRIPTOR' : _RESOLVEFOREIGNEVENTSINTICKETREQUEST,
  '__module__' : 'ots.resolve_foreign_events_in_ticket_pb2'
  # @@protoc_insertion_point(class_scope:ots.ResolveForeignEventsInTicketRequest)
  })
_sym_db.RegisterMessage(ResolveForeignEventsInTicketRequest)

ResolveForeignEventsInTicketResponse = _reflection.GeneratedProtocolMessageType('ResolveForeignEventsInTicketResponse', (_message.Message,), {
  'DESCRIPTOR' : _RESOLVEFOREIGNEVENTSINTICKETRESPONSE,
  '__module__' : 'ots.resolve_foreign_events_in_ticket_pb2'
  # @@protoc_insertion_point(class_scope:ots.ResolveForeignEventsInTicketResponse)
  })
_sym_db.RegisterMessage(ResolveForeignEventsInTicketResponse)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
