// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ots/ticket_max_stake.proto

package com.oddin.ots;

public final class TicketMaxStake {
  private TicketMaxStake() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  @java.lang.Deprecated public interface TicketMaxStakeRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ots.TicketMaxStakeRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.ots.Ticket ticket = 1;</code>
     * @return Whether the ticket field is set.
     */
    boolean hasTicket();
    /**
     * <code>.ots.Ticket ticket = 1;</code>
     * @return The ticket.
     */
    com.oddin.ots.TicketOuterClass.Ticket getTicket();
    /**
     * <code>.ots.Ticket ticket = 1;</code>
     */
    com.oddin.ots.TicketOuterClass.TicketOrBuilder getTicketOrBuilder();
  }
  /**
   * Protobuf type {@code ots.TicketMaxStakeRequest}
   */
  @java.lang.Deprecated public static final class TicketMaxStakeRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ots.TicketMaxStakeRequest)
      TicketMaxStakeRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TicketMaxStakeRequest.newBuilder() to construct.
    private TicketMaxStakeRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TicketMaxStakeRequest() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new TicketMaxStakeRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TicketMaxStakeRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.oddin.ots.TicketOuterClass.Ticket.Builder subBuilder = null;
              if (ticket_ != null) {
                subBuilder = ticket_.toBuilder();
              }
              ticket_ = input.readMessage(com.oddin.ots.TicketOuterClass.Ticket.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(ticket_);
                ticket_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.oddin.ots.TicketMaxStake.internal_static_ots_TicketMaxStakeRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.oddin.ots.TicketMaxStake.internal_static_ots_TicketMaxStakeRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.oddin.ots.TicketMaxStake.TicketMaxStakeRequest.class, com.oddin.ots.TicketMaxStake.TicketMaxStakeRequest.Builder.class);
    }

    public static final int TICKET_FIELD_NUMBER = 1;
    private com.oddin.ots.TicketOuterClass.Ticket ticket_;
    /**
     * <code>.ots.Ticket ticket = 1;</code>
     * @return Whether the ticket field is set.
     */
    @java.lang.Override
    public boolean hasTicket() {
      return ticket_ != null;
    }
    /**
     * <code>.ots.Ticket ticket = 1;</code>
     * @return The ticket.
     */
    @java.lang.Override
    public com.oddin.ots.TicketOuterClass.Ticket getTicket() {
      return ticket_ == null ? com.oddin.ots.TicketOuterClass.Ticket.getDefaultInstance() : ticket_;
    }
    /**
     * <code>.ots.Ticket ticket = 1;</code>
     */
    @java.lang.Override
    public com.oddin.ots.TicketOuterClass.TicketOrBuilder getTicketOrBuilder() {
      return getTicket();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (ticket_ != null) {
        output.writeMessage(1, getTicket());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (ticket_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getTicket());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.oddin.ots.TicketMaxStake.TicketMaxStakeRequest)) {
        return super.equals(obj);
      }
      com.oddin.ots.TicketMaxStake.TicketMaxStakeRequest other = (com.oddin.ots.TicketMaxStake.TicketMaxStakeRequest) obj;

      if (hasTicket() != other.hasTicket()) return false;
      if (hasTicket()) {
        if (!getTicket()
            .equals(other.getTicket())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasTicket()) {
        hash = (37 * hash) + TICKET_FIELD_NUMBER;
        hash = (53 * hash) + getTicket().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.oddin.ots.TicketMaxStake.TicketMaxStakeRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.oddin.ots.TicketMaxStake.TicketMaxStakeRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.oddin.ots.TicketMaxStake.TicketMaxStakeRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.oddin.ots.TicketMaxStake.TicketMaxStakeRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.oddin.ots.TicketMaxStake.TicketMaxStakeRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.oddin.ots.TicketMaxStake.TicketMaxStakeRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.oddin.ots.TicketMaxStake.TicketMaxStakeRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.oddin.ots.TicketMaxStake.TicketMaxStakeRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.oddin.ots.TicketMaxStake.TicketMaxStakeRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.oddin.ots.TicketMaxStake.TicketMaxStakeRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.oddin.ots.TicketMaxStake.TicketMaxStakeRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.oddin.ots.TicketMaxStake.TicketMaxStakeRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.oddin.ots.TicketMaxStake.TicketMaxStakeRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ots.TicketMaxStakeRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ots.TicketMaxStakeRequest)
        com.oddin.ots.TicketMaxStake.TicketMaxStakeRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.oddin.ots.TicketMaxStake.internal_static_ots_TicketMaxStakeRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.oddin.ots.TicketMaxStake.internal_static_ots_TicketMaxStakeRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.oddin.ots.TicketMaxStake.TicketMaxStakeRequest.class, com.oddin.ots.TicketMaxStake.TicketMaxStakeRequest.Builder.class);
      }

      // Construct using com.oddin.ots.TicketMaxStake.TicketMaxStakeRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (ticketBuilder_ == null) {
          ticket_ = null;
        } else {
          ticket_ = null;
          ticketBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.oddin.ots.TicketMaxStake.internal_static_ots_TicketMaxStakeRequest_descriptor;
      }

      @java.lang.Override
      public com.oddin.ots.TicketMaxStake.TicketMaxStakeRequest getDefaultInstanceForType() {
        return com.oddin.ots.TicketMaxStake.TicketMaxStakeRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.oddin.ots.TicketMaxStake.TicketMaxStakeRequest build() {
        com.oddin.ots.TicketMaxStake.TicketMaxStakeRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.oddin.ots.TicketMaxStake.TicketMaxStakeRequest buildPartial() {
        com.oddin.ots.TicketMaxStake.TicketMaxStakeRequest result = new com.oddin.ots.TicketMaxStake.TicketMaxStakeRequest(this);
        if (ticketBuilder_ == null) {
          result.ticket_ = ticket_;
        } else {
          result.ticket_ = ticketBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.oddin.ots.TicketMaxStake.TicketMaxStakeRequest) {
          return mergeFrom((com.oddin.ots.TicketMaxStake.TicketMaxStakeRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.oddin.ots.TicketMaxStake.TicketMaxStakeRequest other) {
        if (other == com.oddin.ots.TicketMaxStake.TicketMaxStakeRequest.getDefaultInstance()) return this;
        if (other.hasTicket()) {
          mergeTicket(other.getTicket());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.oddin.ots.TicketMaxStake.TicketMaxStakeRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.oddin.ots.TicketMaxStake.TicketMaxStakeRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.oddin.ots.TicketOuterClass.Ticket ticket_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.oddin.ots.TicketOuterClass.Ticket, com.oddin.ots.TicketOuterClass.Ticket.Builder, com.oddin.ots.TicketOuterClass.TicketOrBuilder> ticketBuilder_;
      /**
       * <code>.ots.Ticket ticket = 1;</code>
       * @return Whether the ticket field is set.
       */
      public boolean hasTicket() {
        return ticketBuilder_ != null || ticket_ != null;
      }
      /**
       * <code>.ots.Ticket ticket = 1;</code>
       * @return The ticket.
       */
      public com.oddin.ots.TicketOuterClass.Ticket getTicket() {
        if (ticketBuilder_ == null) {
          return ticket_ == null ? com.oddin.ots.TicketOuterClass.Ticket.getDefaultInstance() : ticket_;
        } else {
          return ticketBuilder_.getMessage();
        }
      }
      /**
       * <code>.ots.Ticket ticket = 1;</code>
       */
      public Builder setTicket(com.oddin.ots.TicketOuterClass.Ticket value) {
        if (ticketBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ticket_ = value;
          onChanged();
        } else {
          ticketBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.ots.Ticket ticket = 1;</code>
       */
      public Builder setTicket(
          com.oddin.ots.TicketOuterClass.Ticket.Builder builderForValue) {
        if (ticketBuilder_ == null) {
          ticket_ = builderForValue.build();
          onChanged();
        } else {
          ticketBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.ots.Ticket ticket = 1;</code>
       */
      public Builder mergeTicket(com.oddin.ots.TicketOuterClass.Ticket value) {
        if (ticketBuilder_ == null) {
          if (ticket_ != null) {
            ticket_ =
              com.oddin.ots.TicketOuterClass.Ticket.newBuilder(ticket_).mergeFrom(value).buildPartial();
          } else {
            ticket_ = value;
          }
          onChanged();
        } else {
          ticketBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.ots.Ticket ticket = 1;</code>
       */
      public Builder clearTicket() {
        if (ticketBuilder_ == null) {
          ticket_ = null;
          onChanged();
        } else {
          ticket_ = null;
          ticketBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.ots.Ticket ticket = 1;</code>
       */
      public com.oddin.ots.TicketOuterClass.Ticket.Builder getTicketBuilder() {
        
        onChanged();
        return getTicketFieldBuilder().getBuilder();
      }
      /**
       * <code>.ots.Ticket ticket = 1;</code>
       */
      public com.oddin.ots.TicketOuterClass.TicketOrBuilder getTicketOrBuilder() {
        if (ticketBuilder_ != null) {
          return ticketBuilder_.getMessageOrBuilder();
        } else {
          return ticket_ == null ?
              com.oddin.ots.TicketOuterClass.Ticket.getDefaultInstance() : ticket_;
        }
      }
      /**
       * <code>.ots.Ticket ticket = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.oddin.ots.TicketOuterClass.Ticket, com.oddin.ots.TicketOuterClass.Ticket.Builder, com.oddin.ots.TicketOuterClass.TicketOrBuilder> 
          getTicketFieldBuilder() {
        if (ticketBuilder_ == null) {
          ticketBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.oddin.ots.TicketOuterClass.Ticket, com.oddin.ots.TicketOuterClass.Ticket.Builder, com.oddin.ots.TicketOuterClass.TicketOrBuilder>(
                  getTicket(),
                  getParentForChildren(),
                  isClean());
          ticket_ = null;
        }
        return ticketBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ots.TicketMaxStakeRequest)
    }

    // @@protoc_insertion_point(class_scope:ots.TicketMaxStakeRequest)
    private static final com.oddin.ots.TicketMaxStake.TicketMaxStakeRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.oddin.ots.TicketMaxStake.TicketMaxStakeRequest();
    }

    public static com.oddin.ots.TicketMaxStake.TicketMaxStakeRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TicketMaxStakeRequest>
        PARSER = new com.google.protobuf.AbstractParser<TicketMaxStakeRequest>() {
      @java.lang.Override
      public TicketMaxStakeRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TicketMaxStakeRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TicketMaxStakeRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TicketMaxStakeRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.oddin.ots.TicketMaxStake.TicketMaxStakeRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  @java.lang.Deprecated public interface TicketMaxStakeResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ots.TicketMaxStakeResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.ots.TicketState state = 1;</code>
     * @return Whether the state field is set.
     */
    boolean hasState();
    /**
     * <code>.ots.TicketState state = 1;</code>
     * @return The state.
     */
    com.oddin.ots.TicketOuterClass.TicketState getState();
    /**
     * <code>.ots.TicketState state = 1;</code>
     */
    com.oddin.ots.TicketOuterClass.TicketStateOrBuilder getStateOrBuilder();
  }
  /**
   * Protobuf type {@code ots.TicketMaxStakeResponse}
   */
  @java.lang.Deprecated public static final class TicketMaxStakeResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ots.TicketMaxStakeResponse)
      TicketMaxStakeResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TicketMaxStakeResponse.newBuilder() to construct.
    private TicketMaxStakeResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TicketMaxStakeResponse() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new TicketMaxStakeResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TicketMaxStakeResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.oddin.ots.TicketOuterClass.TicketState.Builder subBuilder = null;
              if (state_ != null) {
                subBuilder = state_.toBuilder();
              }
              state_ = input.readMessage(com.oddin.ots.TicketOuterClass.TicketState.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(state_);
                state_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.oddin.ots.TicketMaxStake.internal_static_ots_TicketMaxStakeResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.oddin.ots.TicketMaxStake.internal_static_ots_TicketMaxStakeResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.oddin.ots.TicketMaxStake.TicketMaxStakeResponse.class, com.oddin.ots.TicketMaxStake.TicketMaxStakeResponse.Builder.class);
    }

    public static final int STATE_FIELD_NUMBER = 1;
    private com.oddin.ots.TicketOuterClass.TicketState state_;
    /**
     * <code>.ots.TicketState state = 1;</code>
     * @return Whether the state field is set.
     */
    @java.lang.Override
    public boolean hasState() {
      return state_ != null;
    }
    /**
     * <code>.ots.TicketState state = 1;</code>
     * @return The state.
     */
    @java.lang.Override
    public com.oddin.ots.TicketOuterClass.TicketState getState() {
      return state_ == null ? com.oddin.ots.TicketOuterClass.TicketState.getDefaultInstance() : state_;
    }
    /**
     * <code>.ots.TicketState state = 1;</code>
     */
    @java.lang.Override
    public com.oddin.ots.TicketOuterClass.TicketStateOrBuilder getStateOrBuilder() {
      return getState();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (state_ != null) {
        output.writeMessage(1, getState());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (state_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getState());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.oddin.ots.TicketMaxStake.TicketMaxStakeResponse)) {
        return super.equals(obj);
      }
      com.oddin.ots.TicketMaxStake.TicketMaxStakeResponse other = (com.oddin.ots.TicketMaxStake.TicketMaxStakeResponse) obj;

      if (hasState() != other.hasState()) return false;
      if (hasState()) {
        if (!getState()
            .equals(other.getState())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasState()) {
        hash = (37 * hash) + STATE_FIELD_NUMBER;
        hash = (53 * hash) + getState().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.oddin.ots.TicketMaxStake.TicketMaxStakeResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.oddin.ots.TicketMaxStake.TicketMaxStakeResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.oddin.ots.TicketMaxStake.TicketMaxStakeResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.oddin.ots.TicketMaxStake.TicketMaxStakeResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.oddin.ots.TicketMaxStake.TicketMaxStakeResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.oddin.ots.TicketMaxStake.TicketMaxStakeResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.oddin.ots.TicketMaxStake.TicketMaxStakeResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.oddin.ots.TicketMaxStake.TicketMaxStakeResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.oddin.ots.TicketMaxStake.TicketMaxStakeResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.oddin.ots.TicketMaxStake.TicketMaxStakeResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.oddin.ots.TicketMaxStake.TicketMaxStakeResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.oddin.ots.TicketMaxStake.TicketMaxStakeResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.oddin.ots.TicketMaxStake.TicketMaxStakeResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ots.TicketMaxStakeResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ots.TicketMaxStakeResponse)
        com.oddin.ots.TicketMaxStake.TicketMaxStakeResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.oddin.ots.TicketMaxStake.internal_static_ots_TicketMaxStakeResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.oddin.ots.TicketMaxStake.internal_static_ots_TicketMaxStakeResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.oddin.ots.TicketMaxStake.TicketMaxStakeResponse.class, com.oddin.ots.TicketMaxStake.TicketMaxStakeResponse.Builder.class);
      }

      // Construct using com.oddin.ots.TicketMaxStake.TicketMaxStakeResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (stateBuilder_ == null) {
          state_ = null;
        } else {
          state_ = null;
          stateBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.oddin.ots.TicketMaxStake.internal_static_ots_TicketMaxStakeResponse_descriptor;
      }

      @java.lang.Override
      public com.oddin.ots.TicketMaxStake.TicketMaxStakeResponse getDefaultInstanceForType() {
        return com.oddin.ots.TicketMaxStake.TicketMaxStakeResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.oddin.ots.TicketMaxStake.TicketMaxStakeResponse build() {
        com.oddin.ots.TicketMaxStake.TicketMaxStakeResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.oddin.ots.TicketMaxStake.TicketMaxStakeResponse buildPartial() {
        com.oddin.ots.TicketMaxStake.TicketMaxStakeResponse result = new com.oddin.ots.TicketMaxStake.TicketMaxStakeResponse(this);
        if (stateBuilder_ == null) {
          result.state_ = state_;
        } else {
          result.state_ = stateBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.oddin.ots.TicketMaxStake.TicketMaxStakeResponse) {
          return mergeFrom((com.oddin.ots.TicketMaxStake.TicketMaxStakeResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.oddin.ots.TicketMaxStake.TicketMaxStakeResponse other) {
        if (other == com.oddin.ots.TicketMaxStake.TicketMaxStakeResponse.getDefaultInstance()) return this;
        if (other.hasState()) {
          mergeState(other.getState());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.oddin.ots.TicketMaxStake.TicketMaxStakeResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.oddin.ots.TicketMaxStake.TicketMaxStakeResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.oddin.ots.TicketOuterClass.TicketState state_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.oddin.ots.TicketOuterClass.TicketState, com.oddin.ots.TicketOuterClass.TicketState.Builder, com.oddin.ots.TicketOuterClass.TicketStateOrBuilder> stateBuilder_;
      /**
       * <code>.ots.TicketState state = 1;</code>
       * @return Whether the state field is set.
       */
      public boolean hasState() {
        return stateBuilder_ != null || state_ != null;
      }
      /**
       * <code>.ots.TicketState state = 1;</code>
       * @return The state.
       */
      public com.oddin.ots.TicketOuterClass.TicketState getState() {
        if (stateBuilder_ == null) {
          return state_ == null ? com.oddin.ots.TicketOuterClass.TicketState.getDefaultInstance() : state_;
        } else {
          return stateBuilder_.getMessage();
        }
      }
      /**
       * <code>.ots.TicketState state = 1;</code>
       */
      public Builder setState(com.oddin.ots.TicketOuterClass.TicketState value) {
        if (stateBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          state_ = value;
          onChanged();
        } else {
          stateBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.ots.TicketState state = 1;</code>
       */
      public Builder setState(
          com.oddin.ots.TicketOuterClass.TicketState.Builder builderForValue) {
        if (stateBuilder_ == null) {
          state_ = builderForValue.build();
          onChanged();
        } else {
          stateBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.ots.TicketState state = 1;</code>
       */
      public Builder mergeState(com.oddin.ots.TicketOuterClass.TicketState value) {
        if (stateBuilder_ == null) {
          if (state_ != null) {
            state_ =
              com.oddin.ots.TicketOuterClass.TicketState.newBuilder(state_).mergeFrom(value).buildPartial();
          } else {
            state_ = value;
          }
          onChanged();
        } else {
          stateBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.ots.TicketState state = 1;</code>
       */
      public Builder clearState() {
        if (stateBuilder_ == null) {
          state_ = null;
          onChanged();
        } else {
          state_ = null;
          stateBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.ots.TicketState state = 1;</code>
       */
      public com.oddin.ots.TicketOuterClass.TicketState.Builder getStateBuilder() {
        
        onChanged();
        return getStateFieldBuilder().getBuilder();
      }
      /**
       * <code>.ots.TicketState state = 1;</code>
       */
      public com.oddin.ots.TicketOuterClass.TicketStateOrBuilder getStateOrBuilder() {
        if (stateBuilder_ != null) {
          return stateBuilder_.getMessageOrBuilder();
        } else {
          return state_ == null ?
              com.oddin.ots.TicketOuterClass.TicketState.getDefaultInstance() : state_;
        }
      }
      /**
       * <code>.ots.TicketState state = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.oddin.ots.TicketOuterClass.TicketState, com.oddin.ots.TicketOuterClass.TicketState.Builder, com.oddin.ots.TicketOuterClass.TicketStateOrBuilder> 
          getStateFieldBuilder() {
        if (stateBuilder_ == null) {
          stateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.oddin.ots.TicketOuterClass.TicketState, com.oddin.ots.TicketOuterClass.TicketState.Builder, com.oddin.ots.TicketOuterClass.TicketStateOrBuilder>(
                  getState(),
                  getParentForChildren(),
                  isClean());
          state_ = null;
        }
        return stateBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ots.TicketMaxStakeResponse)
    }

    // @@protoc_insertion_point(class_scope:ots.TicketMaxStakeResponse)
    private static final com.oddin.ots.TicketMaxStake.TicketMaxStakeResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.oddin.ots.TicketMaxStake.TicketMaxStakeResponse();
    }

    public static com.oddin.ots.TicketMaxStake.TicketMaxStakeResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TicketMaxStakeResponse>
        PARSER = new com.google.protobuf.AbstractParser<TicketMaxStakeResponse>() {
      @java.lang.Override
      public TicketMaxStakeResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TicketMaxStakeResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TicketMaxStakeResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TicketMaxStakeResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.oddin.ots.TicketMaxStake.TicketMaxStakeResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ots_TicketMaxStakeRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ots_TicketMaxStakeRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ots_TicketMaxStakeResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ots_TicketMaxStakeResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032ots/ticket_max_stake.proto\022\003ots\032\020ots/t" +
      "icket.proto\"8\n\025TicketMaxStakeRequest\022\033\n\006" +
      "ticket\030\001 \001(\0132\013.ots.Ticket:\002\030\001\"=\n\026TicketM" +
      "axStakeResponse\022\037\n\005state\030\001 \001(\0132\020.ots.Tic" +
      "ketState:\002\030\001B\035\n\rcom.oddin.otsZ\014oddin.gg/" +
      "otsb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.oddin.ots.TicketOuterClass.getDescriptor(),
        });
    internal_static_ots_TicketMaxStakeRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ots_TicketMaxStakeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ots_TicketMaxStakeRequest_descriptor,
        new java.lang.String[] { "Ticket", });
    internal_static_ots_TicketMaxStakeResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ots_TicketMaxStakeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ots_TicketMaxStakeResponse_descriptor,
        new java.lang.String[] { "State", });
    com.oddin.ots.TicketOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
