// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ots/player_risk_score.proto

package com.oddin.ots;

public final class PlayerRiskScoreOuterClass {
  private PlayerRiskScoreOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PlayerRiskScoreRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ots.PlayerRiskScoreRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    java.lang.String getId();
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString
        getIdBytes();
  }
  /**
   * Protobuf type {@code ots.PlayerRiskScoreRequest}
   */
  public static final class PlayerRiskScoreRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ots.PlayerRiskScoreRequest)
      PlayerRiskScoreRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PlayerRiskScoreRequest.newBuilder() to construct.
    private PlayerRiskScoreRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PlayerRiskScoreRequest() {
      id_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PlayerRiskScoreRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PlayerRiskScoreRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.oddin.ots.PlayerRiskScoreOuterClass.internal_static_ots_PlayerRiskScoreRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.oddin.ots.PlayerRiskScoreOuterClass.internal_static_ots_PlayerRiskScoreRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScoreRequest.class, com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScoreRequest.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object id_;
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScoreRequest)) {
        return super.equals(obj);
      }
      com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScoreRequest other = (com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScoreRequest) obj;

      if (!getId()
          .equals(other.getId())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScoreRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScoreRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScoreRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScoreRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScoreRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScoreRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScoreRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScoreRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScoreRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScoreRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScoreRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScoreRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScoreRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ots.PlayerRiskScoreRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ots.PlayerRiskScoreRequest)
        com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScoreRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.oddin.ots.PlayerRiskScoreOuterClass.internal_static_ots_PlayerRiskScoreRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.oddin.ots.PlayerRiskScoreOuterClass.internal_static_ots_PlayerRiskScoreRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScoreRequest.class, com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScoreRequest.Builder.class);
      }

      // Construct using com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScoreRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.oddin.ots.PlayerRiskScoreOuterClass.internal_static_ots_PlayerRiskScoreRequest_descriptor;
      }

      @java.lang.Override
      public com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScoreRequest getDefaultInstanceForType() {
        return com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScoreRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScoreRequest build() {
        com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScoreRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScoreRequest buildPartial() {
        com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScoreRequest result = new com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScoreRequest(this);
        result.id_ = id_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScoreRequest) {
          return mergeFrom((com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScoreRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScoreRequest other) {
        if (other == com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScoreRequest.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScoreRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScoreRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 1;</code>
       * @return The id.
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @return The bytes for id.
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @param value The bytes for id to set.
       * @return This builder for chaining.
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ots.PlayerRiskScoreRequest)
    }

    // @@protoc_insertion_point(class_scope:ots.PlayerRiskScoreRequest)
    private static final com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScoreRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScoreRequest();
    }

    public static com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScoreRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PlayerRiskScoreRequest>
        PARSER = new com.google.protobuf.AbstractParser<PlayerRiskScoreRequest>() {
      @java.lang.Override
      public PlayerRiskScoreRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PlayerRiskScoreRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PlayerRiskScoreRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PlayerRiskScoreRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScoreRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PlayerRiskScoreResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ots.PlayerRiskScoreResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .ots.PlayerRiskScore risk_scores = 1;</code>
     */
    java.util.List<com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScore> 
        getRiskScoresList();
    /**
     * <code>repeated .ots.PlayerRiskScore risk_scores = 1;</code>
     */
    com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScore getRiskScores(int index);
    /**
     * <code>repeated .ots.PlayerRiskScore risk_scores = 1;</code>
     */
    int getRiskScoresCount();
    /**
     * <code>repeated .ots.PlayerRiskScore risk_scores = 1;</code>
     */
    java.util.List<? extends com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScoreOrBuilder> 
        getRiskScoresOrBuilderList();
    /**
     * <code>repeated .ots.PlayerRiskScore risk_scores = 1;</code>
     */
    com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScoreOrBuilder getRiskScoresOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code ots.PlayerRiskScoreResponse}
   */
  public static final class PlayerRiskScoreResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ots.PlayerRiskScoreResponse)
      PlayerRiskScoreResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PlayerRiskScoreResponse.newBuilder() to construct.
    private PlayerRiskScoreResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PlayerRiskScoreResponse() {
      riskScores_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PlayerRiskScoreResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PlayerRiskScoreResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                riskScores_ = new java.util.ArrayList<com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScore>();
                mutable_bitField0_ |= 0x00000001;
              }
              riskScores_.add(
                  input.readMessage(com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScore.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          riskScores_ = java.util.Collections.unmodifiableList(riskScores_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.oddin.ots.PlayerRiskScoreOuterClass.internal_static_ots_PlayerRiskScoreResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.oddin.ots.PlayerRiskScoreOuterClass.internal_static_ots_PlayerRiskScoreResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScoreResponse.class, com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScoreResponse.Builder.class);
    }

    public static final int RISK_SCORES_FIELD_NUMBER = 1;
    private java.util.List<com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScore> riskScores_;
    /**
     * <code>repeated .ots.PlayerRiskScore risk_scores = 1;</code>
     */
    @java.lang.Override
    public java.util.List<com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScore> getRiskScoresList() {
      return riskScores_;
    }
    /**
     * <code>repeated .ots.PlayerRiskScore risk_scores = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScoreOrBuilder> 
        getRiskScoresOrBuilderList() {
      return riskScores_;
    }
    /**
     * <code>repeated .ots.PlayerRiskScore risk_scores = 1;</code>
     */
    @java.lang.Override
    public int getRiskScoresCount() {
      return riskScores_.size();
    }
    /**
     * <code>repeated .ots.PlayerRiskScore risk_scores = 1;</code>
     */
    @java.lang.Override
    public com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScore getRiskScores(int index) {
      return riskScores_.get(index);
    }
    /**
     * <code>repeated .ots.PlayerRiskScore risk_scores = 1;</code>
     */
    @java.lang.Override
    public com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScoreOrBuilder getRiskScoresOrBuilder(
        int index) {
      return riskScores_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < riskScores_.size(); i++) {
        output.writeMessage(1, riskScores_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < riskScores_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, riskScores_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScoreResponse)) {
        return super.equals(obj);
      }
      com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScoreResponse other = (com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScoreResponse) obj;

      if (!getRiskScoresList()
          .equals(other.getRiskScoresList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getRiskScoresCount() > 0) {
        hash = (37 * hash) + RISK_SCORES_FIELD_NUMBER;
        hash = (53 * hash) + getRiskScoresList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScoreResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScoreResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScoreResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScoreResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScoreResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScoreResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScoreResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScoreResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScoreResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScoreResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScoreResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScoreResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScoreResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ots.PlayerRiskScoreResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ots.PlayerRiskScoreResponse)
        com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScoreResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.oddin.ots.PlayerRiskScoreOuterClass.internal_static_ots_PlayerRiskScoreResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.oddin.ots.PlayerRiskScoreOuterClass.internal_static_ots_PlayerRiskScoreResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScoreResponse.class, com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScoreResponse.Builder.class);
      }

      // Construct using com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScoreResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getRiskScoresFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (riskScoresBuilder_ == null) {
          riskScores_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          riskScoresBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.oddin.ots.PlayerRiskScoreOuterClass.internal_static_ots_PlayerRiskScoreResponse_descriptor;
      }

      @java.lang.Override
      public com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScoreResponse getDefaultInstanceForType() {
        return com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScoreResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScoreResponse build() {
        com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScoreResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScoreResponse buildPartial() {
        com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScoreResponse result = new com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScoreResponse(this);
        int from_bitField0_ = bitField0_;
        if (riskScoresBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            riskScores_ = java.util.Collections.unmodifiableList(riskScores_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.riskScores_ = riskScores_;
        } else {
          result.riskScores_ = riskScoresBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScoreResponse) {
          return mergeFrom((com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScoreResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScoreResponse other) {
        if (other == com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScoreResponse.getDefaultInstance()) return this;
        if (riskScoresBuilder_ == null) {
          if (!other.riskScores_.isEmpty()) {
            if (riskScores_.isEmpty()) {
              riskScores_ = other.riskScores_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureRiskScoresIsMutable();
              riskScores_.addAll(other.riskScores_);
            }
            onChanged();
          }
        } else {
          if (!other.riskScores_.isEmpty()) {
            if (riskScoresBuilder_.isEmpty()) {
              riskScoresBuilder_.dispose();
              riskScoresBuilder_ = null;
              riskScores_ = other.riskScores_;
              bitField0_ = (bitField0_ & ~0x00000001);
              riskScoresBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getRiskScoresFieldBuilder() : null;
            } else {
              riskScoresBuilder_.addAllMessages(other.riskScores_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScoreResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScoreResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScore> riskScores_ =
        java.util.Collections.emptyList();
      private void ensureRiskScoresIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          riskScores_ = new java.util.ArrayList<com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScore>(riskScores_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScore, com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScore.Builder, com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScoreOrBuilder> riskScoresBuilder_;

      /**
       * <code>repeated .ots.PlayerRiskScore risk_scores = 1;</code>
       */
      public java.util.List<com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScore> getRiskScoresList() {
        if (riskScoresBuilder_ == null) {
          return java.util.Collections.unmodifiableList(riskScores_);
        } else {
          return riskScoresBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .ots.PlayerRiskScore risk_scores = 1;</code>
       */
      public int getRiskScoresCount() {
        if (riskScoresBuilder_ == null) {
          return riskScores_.size();
        } else {
          return riskScoresBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .ots.PlayerRiskScore risk_scores = 1;</code>
       */
      public com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScore getRiskScores(int index) {
        if (riskScoresBuilder_ == null) {
          return riskScores_.get(index);
        } else {
          return riskScoresBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .ots.PlayerRiskScore risk_scores = 1;</code>
       */
      public Builder setRiskScores(
          int index, com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScore value) {
        if (riskScoresBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRiskScoresIsMutable();
          riskScores_.set(index, value);
          onChanged();
        } else {
          riskScoresBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ots.PlayerRiskScore risk_scores = 1;</code>
       */
      public Builder setRiskScores(
          int index, com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScore.Builder builderForValue) {
        if (riskScoresBuilder_ == null) {
          ensureRiskScoresIsMutable();
          riskScores_.set(index, builderForValue.build());
          onChanged();
        } else {
          riskScoresBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ots.PlayerRiskScore risk_scores = 1;</code>
       */
      public Builder addRiskScores(com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScore value) {
        if (riskScoresBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRiskScoresIsMutable();
          riskScores_.add(value);
          onChanged();
        } else {
          riskScoresBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .ots.PlayerRiskScore risk_scores = 1;</code>
       */
      public Builder addRiskScores(
          int index, com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScore value) {
        if (riskScoresBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRiskScoresIsMutable();
          riskScores_.add(index, value);
          onChanged();
        } else {
          riskScoresBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ots.PlayerRiskScore risk_scores = 1;</code>
       */
      public Builder addRiskScores(
          com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScore.Builder builderForValue) {
        if (riskScoresBuilder_ == null) {
          ensureRiskScoresIsMutable();
          riskScores_.add(builderForValue.build());
          onChanged();
        } else {
          riskScoresBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ots.PlayerRiskScore risk_scores = 1;</code>
       */
      public Builder addRiskScores(
          int index, com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScore.Builder builderForValue) {
        if (riskScoresBuilder_ == null) {
          ensureRiskScoresIsMutable();
          riskScores_.add(index, builderForValue.build());
          onChanged();
        } else {
          riskScoresBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ots.PlayerRiskScore risk_scores = 1;</code>
       */
      public Builder addAllRiskScores(
          java.lang.Iterable<? extends com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScore> values) {
        if (riskScoresBuilder_ == null) {
          ensureRiskScoresIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, riskScores_);
          onChanged();
        } else {
          riskScoresBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .ots.PlayerRiskScore risk_scores = 1;</code>
       */
      public Builder clearRiskScores() {
        if (riskScoresBuilder_ == null) {
          riskScores_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          riskScoresBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .ots.PlayerRiskScore risk_scores = 1;</code>
       */
      public Builder removeRiskScores(int index) {
        if (riskScoresBuilder_ == null) {
          ensureRiskScoresIsMutable();
          riskScores_.remove(index);
          onChanged();
        } else {
          riskScoresBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .ots.PlayerRiskScore risk_scores = 1;</code>
       */
      public com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScore.Builder getRiskScoresBuilder(
          int index) {
        return getRiskScoresFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .ots.PlayerRiskScore risk_scores = 1;</code>
       */
      public com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScoreOrBuilder getRiskScoresOrBuilder(
          int index) {
        if (riskScoresBuilder_ == null) {
          return riskScores_.get(index);  } else {
          return riskScoresBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .ots.PlayerRiskScore risk_scores = 1;</code>
       */
      public java.util.List<? extends com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScoreOrBuilder> 
           getRiskScoresOrBuilderList() {
        if (riskScoresBuilder_ != null) {
          return riskScoresBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(riskScores_);
        }
      }
      /**
       * <code>repeated .ots.PlayerRiskScore risk_scores = 1;</code>
       */
      public com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScore.Builder addRiskScoresBuilder() {
        return getRiskScoresFieldBuilder().addBuilder(
            com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScore.getDefaultInstance());
      }
      /**
       * <code>repeated .ots.PlayerRiskScore risk_scores = 1;</code>
       */
      public com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScore.Builder addRiskScoresBuilder(
          int index) {
        return getRiskScoresFieldBuilder().addBuilder(
            index, com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScore.getDefaultInstance());
      }
      /**
       * <code>repeated .ots.PlayerRiskScore risk_scores = 1;</code>
       */
      public java.util.List<com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScore.Builder> 
           getRiskScoresBuilderList() {
        return getRiskScoresFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScore, com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScore.Builder, com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScoreOrBuilder> 
          getRiskScoresFieldBuilder() {
        if (riskScoresBuilder_ == null) {
          riskScoresBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScore, com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScore.Builder, com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScoreOrBuilder>(
                  riskScores_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          riskScores_ = null;
        }
        return riskScoresBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ots.PlayerRiskScoreResponse)
    }

    // @@protoc_insertion_point(class_scope:ots.PlayerRiskScoreResponse)
    private static final com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScoreResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScoreResponse();
    }

    public static com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScoreResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PlayerRiskScoreResponse>
        PARSER = new com.google.protobuf.AbstractParser<PlayerRiskScoreResponse>() {
      @java.lang.Override
      public PlayerRiskScoreResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PlayerRiskScoreResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PlayerRiskScoreResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PlayerRiskScoreResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScoreResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PlayerRiskScoreOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ots.PlayerRiskScore)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string sport_id = 1;</code>
     * @return The sportId.
     */
    java.lang.String getSportId();
    /**
     * <code>string sport_id = 1;</code>
     * @return The bytes for sportId.
     */
    com.google.protobuf.ByteString
        getSportIdBytes();

    /**
     * <code>uint32 prematch = 2;</code>
     * @return The prematch.
     */
    int getPrematch();

    /**
     * <code>uint32 live = 3;</code>
     * @return The live.
     */
    int getLive();
  }
  /**
   * Protobuf type {@code ots.PlayerRiskScore}
   */
  public static final class PlayerRiskScore extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ots.PlayerRiskScore)
      PlayerRiskScoreOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PlayerRiskScore.newBuilder() to construct.
    private PlayerRiskScore(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PlayerRiskScore() {
      sportId_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PlayerRiskScore();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PlayerRiskScore(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              sportId_ = s;
              break;
            }
            case 16: {

              prematch_ = input.readUInt32();
              break;
            }
            case 24: {

              live_ = input.readUInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.oddin.ots.PlayerRiskScoreOuterClass.internal_static_ots_PlayerRiskScore_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.oddin.ots.PlayerRiskScoreOuterClass.internal_static_ots_PlayerRiskScore_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScore.class, com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScore.Builder.class);
    }

    public static final int SPORT_ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object sportId_;
    /**
     * <code>string sport_id = 1;</code>
     * @return The sportId.
     */
    @java.lang.Override
    public java.lang.String getSportId() {
      java.lang.Object ref = sportId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sportId_ = s;
        return s;
      }
    }
    /**
     * <code>string sport_id = 1;</code>
     * @return The bytes for sportId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSportIdBytes() {
      java.lang.Object ref = sportId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sportId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PREMATCH_FIELD_NUMBER = 2;
    private int prematch_;
    /**
     * <code>uint32 prematch = 2;</code>
     * @return The prematch.
     */
    @java.lang.Override
    public int getPrematch() {
      return prematch_;
    }

    public static final int LIVE_FIELD_NUMBER = 3;
    private int live_;
    /**
     * <code>uint32 live = 3;</code>
     * @return The live.
     */
    @java.lang.Override
    public int getLive() {
      return live_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getSportIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, sportId_);
      }
      if (prematch_ != 0) {
        output.writeUInt32(2, prematch_);
      }
      if (live_ != 0) {
        output.writeUInt32(3, live_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getSportIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, sportId_);
      }
      if (prematch_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, prematch_);
      }
      if (live_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, live_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScore)) {
        return super.equals(obj);
      }
      com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScore other = (com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScore) obj;

      if (!getSportId()
          .equals(other.getSportId())) return false;
      if (getPrematch()
          != other.getPrematch()) return false;
      if (getLive()
          != other.getLive()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SPORT_ID_FIELD_NUMBER;
      hash = (53 * hash) + getSportId().hashCode();
      hash = (37 * hash) + PREMATCH_FIELD_NUMBER;
      hash = (53 * hash) + getPrematch();
      hash = (37 * hash) + LIVE_FIELD_NUMBER;
      hash = (53 * hash) + getLive();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScore parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScore parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScore parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScore parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScore parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScore parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScore parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScore parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScore parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScore parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScore parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScore parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScore prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ots.PlayerRiskScore}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ots.PlayerRiskScore)
        com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScoreOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.oddin.ots.PlayerRiskScoreOuterClass.internal_static_ots_PlayerRiskScore_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.oddin.ots.PlayerRiskScoreOuterClass.internal_static_ots_PlayerRiskScore_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScore.class, com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScore.Builder.class);
      }

      // Construct using com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScore.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        sportId_ = "";

        prematch_ = 0;

        live_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.oddin.ots.PlayerRiskScoreOuterClass.internal_static_ots_PlayerRiskScore_descriptor;
      }

      @java.lang.Override
      public com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScore getDefaultInstanceForType() {
        return com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScore.getDefaultInstance();
      }

      @java.lang.Override
      public com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScore build() {
        com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScore result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScore buildPartial() {
        com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScore result = new com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScore(this);
        result.sportId_ = sportId_;
        result.prematch_ = prematch_;
        result.live_ = live_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScore) {
          return mergeFrom((com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScore)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScore other) {
        if (other == com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScore.getDefaultInstance()) return this;
        if (!other.getSportId().isEmpty()) {
          sportId_ = other.sportId_;
          onChanged();
        }
        if (other.getPrematch() != 0) {
          setPrematch(other.getPrematch());
        }
        if (other.getLive() != 0) {
          setLive(other.getLive());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScore parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScore) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object sportId_ = "";
      /**
       * <code>string sport_id = 1;</code>
       * @return The sportId.
       */
      public java.lang.String getSportId() {
        java.lang.Object ref = sportId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sportId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string sport_id = 1;</code>
       * @return The bytes for sportId.
       */
      public com.google.protobuf.ByteString
          getSportIdBytes() {
        java.lang.Object ref = sportId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sportId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string sport_id = 1;</code>
       * @param value The sportId to set.
       * @return This builder for chaining.
       */
      public Builder setSportId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sportId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string sport_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSportId() {
        
        sportId_ = getDefaultInstance().getSportId();
        onChanged();
        return this;
      }
      /**
       * <code>string sport_id = 1;</code>
       * @param value The bytes for sportId to set.
       * @return This builder for chaining.
       */
      public Builder setSportIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        sportId_ = value;
        onChanged();
        return this;
      }

      private int prematch_ ;
      /**
       * <code>uint32 prematch = 2;</code>
       * @return The prematch.
       */
      @java.lang.Override
      public int getPrematch() {
        return prematch_;
      }
      /**
       * <code>uint32 prematch = 2;</code>
       * @param value The prematch to set.
       * @return This builder for chaining.
       */
      public Builder setPrematch(int value) {
        
        prematch_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 prematch = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPrematch() {
        
        prematch_ = 0;
        onChanged();
        return this;
      }

      private int live_ ;
      /**
       * <code>uint32 live = 3;</code>
       * @return The live.
       */
      @java.lang.Override
      public int getLive() {
        return live_;
      }
      /**
       * <code>uint32 live = 3;</code>
       * @param value The live to set.
       * @return This builder for chaining.
       */
      public Builder setLive(int value) {
        
        live_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 live = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearLive() {
        
        live_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ots.PlayerRiskScore)
    }

    // @@protoc_insertion_point(class_scope:ots.PlayerRiskScore)
    private static final com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScore DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScore();
    }

    public static com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScore getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PlayerRiskScore>
        PARSER = new com.google.protobuf.AbstractParser<PlayerRiskScore>() {
      @java.lang.Override
      public PlayerRiskScore parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PlayerRiskScore(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PlayerRiskScore> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PlayerRiskScore> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.oddin.ots.PlayerRiskScoreOuterClass.PlayerRiskScore getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ots_PlayerRiskScoreRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ots_PlayerRiskScoreRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ots_PlayerRiskScoreResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ots_PlayerRiskScoreResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ots_PlayerRiskScore_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ots_PlayerRiskScore_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033ots/player_risk_score.proto\022\003ots\"$\n\026Pl" +
      "ayerRiskScoreRequest\022\n\n\002id\030\001 \001(\t\"D\n\027Play" +
      "erRiskScoreResponse\022)\n\013risk_scores\030\001 \003(\013" +
      "2\024.ots.PlayerRiskScore\"C\n\017PlayerRiskScor" +
      "e\022\020\n\010sport_id\030\001 \001(\t\022\020\n\010prematch\030\002 \001(\r\022\014\n" +
      "\004live\030\003 \001(\rB\035\n\rcom.oddin.otsZ\014oddin.gg/o" +
      "tsb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ots_PlayerRiskScoreRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ots_PlayerRiskScoreRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ots_PlayerRiskScoreRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_ots_PlayerRiskScoreResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ots_PlayerRiskScoreResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ots_PlayerRiskScoreResponse_descriptor,
        new java.lang.String[] { "RiskScores", });
    internal_static_ots_PlayerRiskScore_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ots_PlayerRiskScore_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ots_PlayerRiskScore_descriptor,
        new java.lang.String[] { "SportId", "Prematch", "Live", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
