// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ots/player_risk_score.proto

package com.oddin.ots;

public final class PlayerRiskScore {
  private PlayerRiskScore() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PlayerRiskScoreRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ots.PlayerRiskScoreRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Unique player id from the operator’s system.
     * </pre>
     *
     * <code>string id = 1;</code>
     * @return The id.
     */
    java.lang.String getId();
    /**
     * <pre>
     * Unique player id from the operator’s system.
     * </pre>
     *
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString
        getIdBytes();
  }
  /**
   * <pre>
   * PlayerRiskScoreRequest is used for PlayerRiskScore RPC call.
   * You can use this method to get more insight on individual player risk score.
   * </pre>
   *
   * Protobuf type {@code ots.PlayerRiskScoreRequest}
   */
  public static final class PlayerRiskScoreRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ots.PlayerRiskScoreRequest)
      PlayerRiskScoreRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PlayerRiskScoreRequest.newBuilder() to construct.
    private PlayerRiskScoreRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PlayerRiskScoreRequest() {
      id_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PlayerRiskScoreRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.oddin.ots.PlayerRiskScore.internal_static_ots_PlayerRiskScoreRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.oddin.ots.PlayerRiskScore.internal_static_ots_PlayerRiskScoreRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.oddin.ots.PlayerRiskScore.PlayerRiskScoreRequest.class, com.oddin.ots.PlayerRiskScore.PlayerRiskScoreRequest.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object id_ = "";
    /**
     * <pre>
     * Unique player id from the operator’s system.
     * </pre>
     *
     * <code>string id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Unique player id from the operator’s system.
     * </pre>
     *
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.oddin.ots.PlayerRiskScore.PlayerRiskScoreRequest)) {
        return super.equals(obj);
      }
      com.oddin.ots.PlayerRiskScore.PlayerRiskScoreRequest other = (com.oddin.ots.PlayerRiskScore.PlayerRiskScoreRequest) obj;

      if (!getId()
          .equals(other.getId())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.oddin.ots.PlayerRiskScore.PlayerRiskScoreRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.oddin.ots.PlayerRiskScore.PlayerRiskScoreRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.oddin.ots.PlayerRiskScore.PlayerRiskScoreRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.oddin.ots.PlayerRiskScore.PlayerRiskScoreRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.oddin.ots.PlayerRiskScore.PlayerRiskScoreRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.oddin.ots.PlayerRiskScore.PlayerRiskScoreRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.oddin.ots.PlayerRiskScore.PlayerRiskScoreRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.oddin.ots.PlayerRiskScore.PlayerRiskScoreRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.oddin.ots.PlayerRiskScore.PlayerRiskScoreRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.oddin.ots.PlayerRiskScore.PlayerRiskScoreRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.oddin.ots.PlayerRiskScore.PlayerRiskScoreRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.oddin.ots.PlayerRiskScore.PlayerRiskScoreRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.oddin.ots.PlayerRiskScore.PlayerRiskScoreRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * PlayerRiskScoreRequest is used for PlayerRiskScore RPC call.
     * You can use this method to get more insight on individual player risk score.
     * </pre>
     *
     * Protobuf type {@code ots.PlayerRiskScoreRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ots.PlayerRiskScoreRequest)
        com.oddin.ots.PlayerRiskScore.PlayerRiskScoreRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.oddin.ots.PlayerRiskScore.internal_static_ots_PlayerRiskScoreRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.oddin.ots.PlayerRiskScore.internal_static_ots_PlayerRiskScoreRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.oddin.ots.PlayerRiskScore.PlayerRiskScoreRequest.class, com.oddin.ots.PlayerRiskScore.PlayerRiskScoreRequest.Builder.class);
      }

      // Construct using com.oddin.ots.PlayerRiskScore.PlayerRiskScoreRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.oddin.ots.PlayerRiskScore.internal_static_ots_PlayerRiskScoreRequest_descriptor;
      }

      @java.lang.Override
      public com.oddin.ots.PlayerRiskScore.PlayerRiskScoreRequest getDefaultInstanceForType() {
        return com.oddin.ots.PlayerRiskScore.PlayerRiskScoreRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.oddin.ots.PlayerRiskScore.PlayerRiskScoreRequest build() {
        com.oddin.ots.PlayerRiskScore.PlayerRiskScoreRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.oddin.ots.PlayerRiskScore.PlayerRiskScoreRequest buildPartial() {
        com.oddin.ots.PlayerRiskScore.PlayerRiskScoreRequest result = new com.oddin.ots.PlayerRiskScore.PlayerRiskScoreRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.oddin.ots.PlayerRiskScore.PlayerRiskScoreRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.oddin.ots.PlayerRiskScore.PlayerRiskScoreRequest) {
          return mergeFrom((com.oddin.ots.PlayerRiskScore.PlayerRiskScoreRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.oddin.ots.PlayerRiskScore.PlayerRiskScoreRequest other) {
        if (other == com.oddin.ots.PlayerRiskScore.PlayerRiskScoreRequest.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                id_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object id_ = "";
      /**
       * <pre>
       * Unique player id from the operator’s system.
       * </pre>
       *
       * <code>string id = 1;</code>
       * @return The id.
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Unique player id from the operator’s system.
       * </pre>
       *
       * <code>string id = 1;</code>
       * @return The bytes for id.
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Unique player id from the operator’s system.
       * </pre>
       *
       * <code>string id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Unique player id from the operator’s system.
       * </pre>
       *
       * <code>string id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        id_ = getDefaultInstance().getId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Unique player id from the operator’s system.
       * </pre>
       *
       * <code>string id = 1;</code>
       * @param value The bytes for id to set.
       * @return This builder for chaining.
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ots.PlayerRiskScoreRequest)
    }

    // @@protoc_insertion_point(class_scope:ots.PlayerRiskScoreRequest)
    private static final com.oddin.ots.PlayerRiskScore.PlayerRiskScoreRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.oddin.ots.PlayerRiskScore.PlayerRiskScoreRequest();
    }

    public static com.oddin.ots.PlayerRiskScore.PlayerRiskScoreRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PlayerRiskScoreRequest>
        PARSER = new com.google.protobuf.AbstractParser<PlayerRiskScoreRequest>() {
      @java.lang.Override
      public PlayerRiskScoreRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<PlayerRiskScoreRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PlayerRiskScoreRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.oddin.ots.PlayerRiskScore.PlayerRiskScoreRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PlayerRiskScoreResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ots.PlayerRiskScoreResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>float score = 1 [deprecated = true];</code>
     * @deprecated ots.PlayerRiskScoreResponse.score is deprecated.
     *     See ots/player_risk_score.proto;l=15
     * @return The score.
     */
    @java.lang.Deprecated float getScore();

    /**
     * <code>float bos = 2;</code>
     * @return The bos.
     */
    float getBos();

    /**
     * <code>float oaf = 3;</code>
     * @return The oaf.
     */
    float getOaf();

    /**
     * <code>uint32 live_delay = 4;</code>
     * @return The liveDelay.
     */
    int getLiveDelay();

    /**
     * <code>uint32 prematch_delay = 5;</code>
     * @return The prematchDelay.
     */
    int getPrematchDelay();
  }
  /**
   * Protobuf type {@code ots.PlayerRiskScoreResponse}
   */
  public static final class PlayerRiskScoreResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ots.PlayerRiskScoreResponse)
      PlayerRiskScoreResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PlayerRiskScoreResponse.newBuilder() to construct.
    private PlayerRiskScoreResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PlayerRiskScoreResponse() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PlayerRiskScoreResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.oddin.ots.PlayerRiskScore.internal_static_ots_PlayerRiskScoreResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.oddin.ots.PlayerRiskScore.internal_static_ots_PlayerRiskScoreResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.oddin.ots.PlayerRiskScore.PlayerRiskScoreResponse.class, com.oddin.ots.PlayerRiskScore.PlayerRiskScoreResponse.Builder.class);
    }

    public static final int SCORE_FIELD_NUMBER = 1;
    private float score_ = 0F;
    /**
     * <code>float score = 1 [deprecated = true];</code>
     * @deprecated ots.PlayerRiskScoreResponse.score is deprecated.
     *     See ots/player_risk_score.proto;l=15
     * @return The score.
     */
    @java.lang.Override
    @java.lang.Deprecated public float getScore() {
      return score_;
    }

    public static final int BOS_FIELD_NUMBER = 2;
    private float bos_ = 0F;
    /**
     * <code>float bos = 2;</code>
     * @return The bos.
     */
    @java.lang.Override
    public float getBos() {
      return bos_;
    }

    public static final int OAF_FIELD_NUMBER = 3;
    private float oaf_ = 0F;
    /**
     * <code>float oaf = 3;</code>
     * @return The oaf.
     */
    @java.lang.Override
    public float getOaf() {
      return oaf_;
    }

    public static final int LIVE_DELAY_FIELD_NUMBER = 4;
    private int liveDelay_ = 0;
    /**
     * <code>uint32 live_delay = 4;</code>
     * @return The liveDelay.
     */
    @java.lang.Override
    public int getLiveDelay() {
      return liveDelay_;
    }

    public static final int PREMATCH_DELAY_FIELD_NUMBER = 5;
    private int prematchDelay_ = 0;
    /**
     * <code>uint32 prematch_delay = 5;</code>
     * @return The prematchDelay.
     */
    @java.lang.Override
    public int getPrematchDelay() {
      return prematchDelay_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (java.lang.Float.floatToRawIntBits(score_) != 0) {
        output.writeFloat(1, score_);
      }
      if (java.lang.Float.floatToRawIntBits(bos_) != 0) {
        output.writeFloat(2, bos_);
      }
      if (java.lang.Float.floatToRawIntBits(oaf_) != 0) {
        output.writeFloat(3, oaf_);
      }
      if (liveDelay_ != 0) {
        output.writeUInt32(4, liveDelay_);
      }
      if (prematchDelay_ != 0) {
        output.writeUInt32(5, prematchDelay_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (java.lang.Float.floatToRawIntBits(score_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, score_);
      }
      if (java.lang.Float.floatToRawIntBits(bos_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, bos_);
      }
      if (java.lang.Float.floatToRawIntBits(oaf_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, oaf_);
      }
      if (liveDelay_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, liveDelay_);
      }
      if (prematchDelay_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, prematchDelay_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.oddin.ots.PlayerRiskScore.PlayerRiskScoreResponse)) {
        return super.equals(obj);
      }
      com.oddin.ots.PlayerRiskScore.PlayerRiskScoreResponse other = (com.oddin.ots.PlayerRiskScore.PlayerRiskScoreResponse) obj;

      if (java.lang.Float.floatToIntBits(getScore())
          != java.lang.Float.floatToIntBits(
              other.getScore())) return false;
      if (java.lang.Float.floatToIntBits(getBos())
          != java.lang.Float.floatToIntBits(
              other.getBos())) return false;
      if (java.lang.Float.floatToIntBits(getOaf())
          != java.lang.Float.floatToIntBits(
              other.getOaf())) return false;
      if (getLiveDelay()
          != other.getLiveDelay()) return false;
      if (getPrematchDelay()
          != other.getPrematchDelay()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SCORE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getScore());
      hash = (37 * hash) + BOS_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getBos());
      hash = (37 * hash) + OAF_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getOaf());
      hash = (37 * hash) + LIVE_DELAY_FIELD_NUMBER;
      hash = (53 * hash) + getLiveDelay();
      hash = (37 * hash) + PREMATCH_DELAY_FIELD_NUMBER;
      hash = (53 * hash) + getPrematchDelay();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.oddin.ots.PlayerRiskScore.PlayerRiskScoreResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.oddin.ots.PlayerRiskScore.PlayerRiskScoreResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.oddin.ots.PlayerRiskScore.PlayerRiskScoreResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.oddin.ots.PlayerRiskScore.PlayerRiskScoreResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.oddin.ots.PlayerRiskScore.PlayerRiskScoreResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.oddin.ots.PlayerRiskScore.PlayerRiskScoreResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.oddin.ots.PlayerRiskScore.PlayerRiskScoreResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.oddin.ots.PlayerRiskScore.PlayerRiskScoreResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.oddin.ots.PlayerRiskScore.PlayerRiskScoreResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.oddin.ots.PlayerRiskScore.PlayerRiskScoreResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.oddin.ots.PlayerRiskScore.PlayerRiskScoreResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.oddin.ots.PlayerRiskScore.PlayerRiskScoreResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.oddin.ots.PlayerRiskScore.PlayerRiskScoreResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ots.PlayerRiskScoreResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ots.PlayerRiskScoreResponse)
        com.oddin.ots.PlayerRiskScore.PlayerRiskScoreResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.oddin.ots.PlayerRiskScore.internal_static_ots_PlayerRiskScoreResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.oddin.ots.PlayerRiskScore.internal_static_ots_PlayerRiskScoreResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.oddin.ots.PlayerRiskScore.PlayerRiskScoreResponse.class, com.oddin.ots.PlayerRiskScore.PlayerRiskScoreResponse.Builder.class);
      }

      // Construct using com.oddin.ots.PlayerRiskScore.PlayerRiskScoreResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        score_ = 0F;
        bos_ = 0F;
        oaf_ = 0F;
        liveDelay_ = 0;
        prematchDelay_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.oddin.ots.PlayerRiskScore.internal_static_ots_PlayerRiskScoreResponse_descriptor;
      }

      @java.lang.Override
      public com.oddin.ots.PlayerRiskScore.PlayerRiskScoreResponse getDefaultInstanceForType() {
        return com.oddin.ots.PlayerRiskScore.PlayerRiskScoreResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.oddin.ots.PlayerRiskScore.PlayerRiskScoreResponse build() {
        com.oddin.ots.PlayerRiskScore.PlayerRiskScoreResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.oddin.ots.PlayerRiskScore.PlayerRiskScoreResponse buildPartial() {
        com.oddin.ots.PlayerRiskScore.PlayerRiskScoreResponse result = new com.oddin.ots.PlayerRiskScore.PlayerRiskScoreResponse(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.oddin.ots.PlayerRiskScore.PlayerRiskScoreResponse result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.score_ = score_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.bos_ = bos_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.oaf_ = oaf_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.liveDelay_ = liveDelay_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.prematchDelay_ = prematchDelay_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.oddin.ots.PlayerRiskScore.PlayerRiskScoreResponse) {
          return mergeFrom((com.oddin.ots.PlayerRiskScore.PlayerRiskScoreResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.oddin.ots.PlayerRiskScore.PlayerRiskScoreResponse other) {
        if (other == com.oddin.ots.PlayerRiskScore.PlayerRiskScoreResponse.getDefaultInstance()) return this;
        if (other.getScore() != 0F) {
          setScore(other.getScore());
        }
        if (other.getBos() != 0F) {
          setBos(other.getBos());
        }
        if (other.getOaf() != 0F) {
          setOaf(other.getOaf());
        }
        if (other.getLiveDelay() != 0) {
          setLiveDelay(other.getLiveDelay());
        }
        if (other.getPrematchDelay() != 0) {
          setPrematchDelay(other.getPrematchDelay());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 13: {
                score_ = input.readFloat();
                bitField0_ |= 0x00000001;
                break;
              } // case 13
              case 21: {
                bos_ = input.readFloat();
                bitField0_ |= 0x00000002;
                break;
              } // case 21
              case 29: {
                oaf_ = input.readFloat();
                bitField0_ |= 0x00000004;
                break;
              } // case 29
              case 32: {
                liveDelay_ = input.readUInt32();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 40: {
                prematchDelay_ = input.readUInt32();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private float score_ ;
      /**
       * <code>float score = 1 [deprecated = true];</code>
       * @deprecated ots.PlayerRiskScoreResponse.score is deprecated.
       *     See ots/player_risk_score.proto;l=15
       * @return The score.
       */
      @java.lang.Override
      @java.lang.Deprecated public float getScore() {
        return score_;
      }
      /**
       * <code>float score = 1 [deprecated = true];</code>
       * @deprecated ots.PlayerRiskScoreResponse.score is deprecated.
       *     See ots/player_risk_score.proto;l=15
       * @param value The score to set.
       * @return This builder for chaining.
       */
      @java.lang.Deprecated public Builder setScore(float value) {
        
        score_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>float score = 1 [deprecated = true];</code>
       * @deprecated ots.PlayerRiskScoreResponse.score is deprecated.
       *     See ots/player_risk_score.proto;l=15
       * @return This builder for chaining.
       */
      @java.lang.Deprecated public Builder clearScore() {
        bitField0_ = (bitField0_ & ~0x00000001);
        score_ = 0F;
        onChanged();
        return this;
      }

      private float bos_ ;
      /**
       * <code>float bos = 2;</code>
       * @return The bos.
       */
      @java.lang.Override
      public float getBos() {
        return bos_;
      }
      /**
       * <code>float bos = 2;</code>
       * @param value The bos to set.
       * @return This builder for chaining.
       */
      public Builder setBos(float value) {
        
        bos_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>float bos = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearBos() {
        bitField0_ = (bitField0_ & ~0x00000002);
        bos_ = 0F;
        onChanged();
        return this;
      }

      private float oaf_ ;
      /**
       * <code>float oaf = 3;</code>
       * @return The oaf.
       */
      @java.lang.Override
      public float getOaf() {
        return oaf_;
      }
      /**
       * <code>float oaf = 3;</code>
       * @param value The oaf to set.
       * @return This builder for chaining.
       */
      public Builder setOaf(float value) {
        
        oaf_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>float oaf = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearOaf() {
        bitField0_ = (bitField0_ & ~0x00000004);
        oaf_ = 0F;
        onChanged();
        return this;
      }

      private int liveDelay_ ;
      /**
       * <code>uint32 live_delay = 4;</code>
       * @return The liveDelay.
       */
      @java.lang.Override
      public int getLiveDelay() {
        return liveDelay_;
      }
      /**
       * <code>uint32 live_delay = 4;</code>
       * @param value The liveDelay to set.
       * @return This builder for chaining.
       */
      public Builder setLiveDelay(int value) {
        
        liveDelay_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 live_delay = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearLiveDelay() {
        bitField0_ = (bitField0_ & ~0x00000008);
        liveDelay_ = 0;
        onChanged();
        return this;
      }

      private int prematchDelay_ ;
      /**
       * <code>uint32 prematch_delay = 5;</code>
       * @return The prematchDelay.
       */
      @java.lang.Override
      public int getPrematchDelay() {
        return prematchDelay_;
      }
      /**
       * <code>uint32 prematch_delay = 5;</code>
       * @param value The prematchDelay to set.
       * @return This builder for chaining.
       */
      public Builder setPrematchDelay(int value) {
        
        prematchDelay_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 prematch_delay = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearPrematchDelay() {
        bitField0_ = (bitField0_ & ~0x00000010);
        prematchDelay_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ots.PlayerRiskScoreResponse)
    }

    // @@protoc_insertion_point(class_scope:ots.PlayerRiskScoreResponse)
    private static final com.oddin.ots.PlayerRiskScore.PlayerRiskScoreResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.oddin.ots.PlayerRiskScore.PlayerRiskScoreResponse();
    }

    public static com.oddin.ots.PlayerRiskScore.PlayerRiskScoreResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PlayerRiskScoreResponse>
        PARSER = new com.google.protobuf.AbstractParser<PlayerRiskScoreResponse>() {
      @java.lang.Override
      public PlayerRiskScoreResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<PlayerRiskScoreResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PlayerRiskScoreResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.oddin.ots.PlayerRiskScore.PlayerRiskScoreResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ots_PlayerRiskScoreRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ots_PlayerRiskScoreRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ots_PlayerRiskScoreResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ots_PlayerRiskScoreResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033ots/player_risk_score.proto\022\003ots\"$\n\026Pl" +
      "ayerRiskScoreRequest\022\n\n\002id\030\001 \001(\t\"r\n\027Play" +
      "erRiskScoreResponse\022\021\n\005score\030\001 \001(\002B\002\030\001\022\013" +
      "\n\003bos\030\002 \001(\002\022\013\n\003oaf\030\003 \001(\002\022\022\n\nlive_delay\030\004" +
      " \001(\r\022\026\n\016prematch_delay\030\005 \001(\rB\035\n\rcom.oddi" +
      "n.otsZ\014oddin.gg/otsb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ots_PlayerRiskScoreRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ots_PlayerRiskScoreRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ots_PlayerRiskScoreRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_ots_PlayerRiskScoreResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ots_PlayerRiskScoreResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ots_PlayerRiskScoreResponse_descriptor,
        new java.lang.String[] { "Score", "Bos", "Oaf", "LiveDelay", "PrematchDelay", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
