// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ots/ticket_ack.proto

package com.oddin.ots;

public final class TicketAck {
  private TicketAck() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TicketAckRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ots.TicketAckRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    java.lang.String getId();
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>.google.protobuf.Timestamp timestamp = 2;</code>
     * @return Whether the timestamp field is set.
     */
    boolean hasTimestamp();
    /**
     * <code>.google.protobuf.Timestamp timestamp = 2;</code>
     * @return The timestamp.
     */
    com.google.protobuf.Timestamp getTimestamp();
    /**
     * <code>.google.protobuf.Timestamp timestamp = 2;</code>
     */
    com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder();

    /**
     * <code>.ots.enums.AcceptanceStatus acceptance_status = 3;</code>
     * @return The enum numeric value on the wire for acceptanceStatus.
     */
    int getAcceptanceStatusValue();
    /**
     * <code>.ots.enums.AcceptanceStatus acceptance_status = 3;</code>
     * @return The acceptanceStatus.
     */
    com.oddin.ots.Enums.AcceptanceStatus getAcceptanceStatus();

    /**
     * <code>.ots.enums.Reason reason = 4;</code>
     * @return Whether the reason field is set.
     */
    boolean hasReason();
    /**
     * <code>.ots.enums.Reason reason = 4;</code>
     * @return The reason.
     */
    com.oddin.ots.Enums.Reason getReason();
    /**
     * <code>.ots.enums.Reason reason = 4;</code>
     */
    com.oddin.ots.Enums.ReasonOrBuilder getReasonOrBuilder();
  }
  /**
   * Protobuf type {@code ots.TicketAckRequest}
   */
  public static final class TicketAckRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ots.TicketAckRequest)
      TicketAckRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TicketAckRequest.newBuilder() to construct.
    private TicketAckRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TicketAckRequest() {
      id_ = "";
      acceptanceStatus_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new TicketAckRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TicketAckRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 18: {
              com.google.protobuf.Timestamp.Builder subBuilder = null;
              if (timestamp_ != null) {
                subBuilder = timestamp_.toBuilder();
              }
              timestamp_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(timestamp_);
                timestamp_ = subBuilder.buildPartial();
              }

              break;
            }
            case 24: {
              int rawValue = input.readEnum();

              acceptanceStatus_ = rawValue;
              break;
            }
            case 34: {
              com.oddin.ots.Enums.Reason.Builder subBuilder = null;
              if (reason_ != null) {
                subBuilder = reason_.toBuilder();
              }
              reason_ = input.readMessage(com.oddin.ots.Enums.Reason.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(reason_);
                reason_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.oddin.ots.TicketAck.internal_static_ots_TicketAckRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.oddin.ots.TicketAck.internal_static_ots_TicketAckRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.oddin.ots.TicketAck.TicketAckRequest.class, com.oddin.ots.TicketAck.TicketAckRequest.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object id_;
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 2;
    private com.google.protobuf.Timestamp timestamp_;
    /**
     * <code>.google.protobuf.Timestamp timestamp = 2;</code>
     * @return Whether the timestamp field is set.
     */
    @java.lang.Override
    public boolean hasTimestamp() {
      return timestamp_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 2;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getTimestamp() {
      return timestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 2;</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder() {
      return getTimestamp();
    }

    public static final int ACCEPTANCE_STATUS_FIELD_NUMBER = 3;
    private int acceptanceStatus_;
    /**
     * <code>.ots.enums.AcceptanceStatus acceptance_status = 3;</code>
     * @return The enum numeric value on the wire for acceptanceStatus.
     */
    @java.lang.Override public int getAcceptanceStatusValue() {
      return acceptanceStatus_;
    }
    /**
     * <code>.ots.enums.AcceptanceStatus acceptance_status = 3;</code>
     * @return The acceptanceStatus.
     */
    @java.lang.Override public com.oddin.ots.Enums.AcceptanceStatus getAcceptanceStatus() {
      @SuppressWarnings("deprecation")
      com.oddin.ots.Enums.AcceptanceStatus result = com.oddin.ots.Enums.AcceptanceStatus.valueOf(acceptanceStatus_);
      return result == null ? com.oddin.ots.Enums.AcceptanceStatus.UNRECOGNIZED : result;
    }

    public static final int REASON_FIELD_NUMBER = 4;
    private com.oddin.ots.Enums.Reason reason_;
    /**
     * <code>.ots.enums.Reason reason = 4;</code>
     * @return Whether the reason field is set.
     */
    @java.lang.Override
    public boolean hasReason() {
      return reason_ != null;
    }
    /**
     * <code>.ots.enums.Reason reason = 4;</code>
     * @return The reason.
     */
    @java.lang.Override
    public com.oddin.ots.Enums.Reason getReason() {
      return reason_ == null ? com.oddin.ots.Enums.Reason.getDefaultInstance() : reason_;
    }
    /**
     * <code>.ots.enums.Reason reason = 4;</code>
     */
    @java.lang.Override
    public com.oddin.ots.Enums.ReasonOrBuilder getReasonOrBuilder() {
      return getReason();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (timestamp_ != null) {
        output.writeMessage(2, getTimestamp());
      }
      if (acceptanceStatus_ != com.oddin.ots.Enums.AcceptanceStatus.REJECTED.getNumber()) {
        output.writeEnum(3, acceptanceStatus_);
      }
      if (reason_ != null) {
        output.writeMessage(4, getReason());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (timestamp_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getTimestamp());
      }
      if (acceptanceStatus_ != com.oddin.ots.Enums.AcceptanceStatus.REJECTED.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, acceptanceStatus_);
      }
      if (reason_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getReason());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.oddin.ots.TicketAck.TicketAckRequest)) {
        return super.equals(obj);
      }
      com.oddin.ots.TicketAck.TicketAckRequest other = (com.oddin.ots.TicketAck.TicketAckRequest) obj;

      if (!getId()
          .equals(other.getId())) return false;
      if (hasTimestamp() != other.hasTimestamp()) return false;
      if (hasTimestamp()) {
        if (!getTimestamp()
            .equals(other.getTimestamp())) return false;
      }
      if (acceptanceStatus_ != other.acceptanceStatus_) return false;
      if (hasReason() != other.hasReason()) return false;
      if (hasReason()) {
        if (!getReason()
            .equals(other.getReason())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      if (hasTimestamp()) {
        hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + getTimestamp().hashCode();
      }
      hash = (37 * hash) + ACCEPTANCE_STATUS_FIELD_NUMBER;
      hash = (53 * hash) + acceptanceStatus_;
      if (hasReason()) {
        hash = (37 * hash) + REASON_FIELD_NUMBER;
        hash = (53 * hash) + getReason().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.oddin.ots.TicketAck.TicketAckRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.oddin.ots.TicketAck.TicketAckRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.oddin.ots.TicketAck.TicketAckRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.oddin.ots.TicketAck.TicketAckRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.oddin.ots.TicketAck.TicketAckRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.oddin.ots.TicketAck.TicketAckRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.oddin.ots.TicketAck.TicketAckRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.oddin.ots.TicketAck.TicketAckRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.oddin.ots.TicketAck.TicketAckRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.oddin.ots.TicketAck.TicketAckRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.oddin.ots.TicketAck.TicketAckRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.oddin.ots.TicketAck.TicketAckRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.oddin.ots.TicketAck.TicketAckRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ots.TicketAckRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ots.TicketAckRequest)
        com.oddin.ots.TicketAck.TicketAckRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.oddin.ots.TicketAck.internal_static_ots_TicketAckRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.oddin.ots.TicketAck.internal_static_ots_TicketAckRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.oddin.ots.TicketAck.TicketAckRequest.class, com.oddin.ots.TicketAck.TicketAckRequest.Builder.class);
      }

      // Construct using com.oddin.ots.TicketAck.TicketAckRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = "";

        if (timestampBuilder_ == null) {
          timestamp_ = null;
        } else {
          timestamp_ = null;
          timestampBuilder_ = null;
        }
        acceptanceStatus_ = 0;

        if (reasonBuilder_ == null) {
          reason_ = null;
        } else {
          reason_ = null;
          reasonBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.oddin.ots.TicketAck.internal_static_ots_TicketAckRequest_descriptor;
      }

      @java.lang.Override
      public com.oddin.ots.TicketAck.TicketAckRequest getDefaultInstanceForType() {
        return com.oddin.ots.TicketAck.TicketAckRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.oddin.ots.TicketAck.TicketAckRequest build() {
        com.oddin.ots.TicketAck.TicketAckRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.oddin.ots.TicketAck.TicketAckRequest buildPartial() {
        com.oddin.ots.TicketAck.TicketAckRequest result = new com.oddin.ots.TicketAck.TicketAckRequest(this);
        result.id_ = id_;
        if (timestampBuilder_ == null) {
          result.timestamp_ = timestamp_;
        } else {
          result.timestamp_ = timestampBuilder_.build();
        }
        result.acceptanceStatus_ = acceptanceStatus_;
        if (reasonBuilder_ == null) {
          result.reason_ = reason_;
        } else {
          result.reason_ = reasonBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.oddin.ots.TicketAck.TicketAckRequest) {
          return mergeFrom((com.oddin.ots.TicketAck.TicketAckRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.oddin.ots.TicketAck.TicketAckRequest other) {
        if (other == com.oddin.ots.TicketAck.TicketAckRequest.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (other.hasTimestamp()) {
          mergeTimestamp(other.getTimestamp());
        }
        if (other.acceptanceStatus_ != 0) {
          setAcceptanceStatusValue(other.getAcceptanceStatusValue());
        }
        if (other.hasReason()) {
          mergeReason(other.getReason());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.oddin.ots.TicketAck.TicketAckRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.oddin.ots.TicketAck.TicketAckRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 1;</code>
       * @return The id.
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @return The bytes for id.
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @param value The bytes for id to set.
       * @return This builder for chaining.
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.Timestamp timestamp_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> timestampBuilder_;
      /**
       * <code>.google.protobuf.Timestamp timestamp = 2;</code>
       * @return Whether the timestamp field is set.
       */
      public boolean hasTimestamp() {
        return timestampBuilder_ != null || timestamp_ != null;
      }
      /**
       * <code>.google.protobuf.Timestamp timestamp = 2;</code>
       * @return The timestamp.
       */
      public com.google.protobuf.Timestamp getTimestamp() {
        if (timestampBuilder_ == null) {
          return timestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
        } else {
          return timestampBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp timestamp = 2;</code>
       */
      public Builder setTimestamp(com.google.protobuf.Timestamp value) {
        if (timestampBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          timestamp_ = value;
          onChanged();
        } else {
          timestampBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp timestamp = 2;</code>
       */
      public Builder setTimestamp(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (timestampBuilder_ == null) {
          timestamp_ = builderForValue.build();
          onChanged();
        } else {
          timestampBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp timestamp = 2;</code>
       */
      public Builder mergeTimestamp(com.google.protobuf.Timestamp value) {
        if (timestampBuilder_ == null) {
          if (timestamp_ != null) {
            timestamp_ =
              com.google.protobuf.Timestamp.newBuilder(timestamp_).mergeFrom(value).buildPartial();
          } else {
            timestamp_ = value;
          }
          onChanged();
        } else {
          timestampBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp timestamp = 2;</code>
       */
      public Builder clearTimestamp() {
        if (timestampBuilder_ == null) {
          timestamp_ = null;
          onChanged();
        } else {
          timestamp_ = null;
          timestampBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp timestamp = 2;</code>
       */
      public com.google.protobuf.Timestamp.Builder getTimestampBuilder() {
        
        onChanged();
        return getTimestampFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp timestamp = 2;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder() {
        if (timestampBuilder_ != null) {
          return timestampBuilder_.getMessageOrBuilder();
        } else {
          return timestamp_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp timestamp = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getTimestampFieldBuilder() {
        if (timestampBuilder_ == null) {
          timestampBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getTimestamp(),
                  getParentForChildren(),
                  isClean());
          timestamp_ = null;
        }
        return timestampBuilder_;
      }

      private int acceptanceStatus_ = 0;
      /**
       * <code>.ots.enums.AcceptanceStatus acceptance_status = 3;</code>
       * @return The enum numeric value on the wire for acceptanceStatus.
       */
      @java.lang.Override public int getAcceptanceStatusValue() {
        return acceptanceStatus_;
      }
      /**
       * <code>.ots.enums.AcceptanceStatus acceptance_status = 3;</code>
       * @param value The enum numeric value on the wire for acceptanceStatus to set.
       * @return This builder for chaining.
       */
      public Builder setAcceptanceStatusValue(int value) {
        
        acceptanceStatus_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.ots.enums.AcceptanceStatus acceptance_status = 3;</code>
       * @return The acceptanceStatus.
       */
      @java.lang.Override
      public com.oddin.ots.Enums.AcceptanceStatus getAcceptanceStatus() {
        @SuppressWarnings("deprecation")
        com.oddin.ots.Enums.AcceptanceStatus result = com.oddin.ots.Enums.AcceptanceStatus.valueOf(acceptanceStatus_);
        return result == null ? com.oddin.ots.Enums.AcceptanceStatus.UNRECOGNIZED : result;
      }
      /**
       * <code>.ots.enums.AcceptanceStatus acceptance_status = 3;</code>
       * @param value The acceptanceStatus to set.
       * @return This builder for chaining.
       */
      public Builder setAcceptanceStatus(com.oddin.ots.Enums.AcceptanceStatus value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        acceptanceStatus_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.ots.enums.AcceptanceStatus acceptance_status = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearAcceptanceStatus() {
        
        acceptanceStatus_ = 0;
        onChanged();
        return this;
      }

      private com.oddin.ots.Enums.Reason reason_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.oddin.ots.Enums.Reason, com.oddin.ots.Enums.Reason.Builder, com.oddin.ots.Enums.ReasonOrBuilder> reasonBuilder_;
      /**
       * <code>.ots.enums.Reason reason = 4;</code>
       * @return Whether the reason field is set.
       */
      public boolean hasReason() {
        return reasonBuilder_ != null || reason_ != null;
      }
      /**
       * <code>.ots.enums.Reason reason = 4;</code>
       * @return The reason.
       */
      public com.oddin.ots.Enums.Reason getReason() {
        if (reasonBuilder_ == null) {
          return reason_ == null ? com.oddin.ots.Enums.Reason.getDefaultInstance() : reason_;
        } else {
          return reasonBuilder_.getMessage();
        }
      }
      /**
       * <code>.ots.enums.Reason reason = 4;</code>
       */
      public Builder setReason(com.oddin.ots.Enums.Reason value) {
        if (reasonBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          reason_ = value;
          onChanged();
        } else {
          reasonBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.ots.enums.Reason reason = 4;</code>
       */
      public Builder setReason(
          com.oddin.ots.Enums.Reason.Builder builderForValue) {
        if (reasonBuilder_ == null) {
          reason_ = builderForValue.build();
          onChanged();
        } else {
          reasonBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.ots.enums.Reason reason = 4;</code>
       */
      public Builder mergeReason(com.oddin.ots.Enums.Reason value) {
        if (reasonBuilder_ == null) {
          if (reason_ != null) {
            reason_ =
              com.oddin.ots.Enums.Reason.newBuilder(reason_).mergeFrom(value).buildPartial();
          } else {
            reason_ = value;
          }
          onChanged();
        } else {
          reasonBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.ots.enums.Reason reason = 4;</code>
       */
      public Builder clearReason() {
        if (reasonBuilder_ == null) {
          reason_ = null;
          onChanged();
        } else {
          reason_ = null;
          reasonBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.ots.enums.Reason reason = 4;</code>
       */
      public com.oddin.ots.Enums.Reason.Builder getReasonBuilder() {
        
        onChanged();
        return getReasonFieldBuilder().getBuilder();
      }
      /**
       * <code>.ots.enums.Reason reason = 4;</code>
       */
      public com.oddin.ots.Enums.ReasonOrBuilder getReasonOrBuilder() {
        if (reasonBuilder_ != null) {
          return reasonBuilder_.getMessageOrBuilder();
        } else {
          return reason_ == null ?
              com.oddin.ots.Enums.Reason.getDefaultInstance() : reason_;
        }
      }
      /**
       * <code>.ots.enums.Reason reason = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.oddin.ots.Enums.Reason, com.oddin.ots.Enums.Reason.Builder, com.oddin.ots.Enums.ReasonOrBuilder> 
          getReasonFieldBuilder() {
        if (reasonBuilder_ == null) {
          reasonBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.oddin.ots.Enums.Reason, com.oddin.ots.Enums.Reason.Builder, com.oddin.ots.Enums.ReasonOrBuilder>(
                  getReason(),
                  getParentForChildren(),
                  isClean());
          reason_ = null;
        }
        return reasonBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ots.TicketAckRequest)
    }

    // @@protoc_insertion_point(class_scope:ots.TicketAckRequest)
    private static final com.oddin.ots.TicketAck.TicketAckRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.oddin.ots.TicketAck.TicketAckRequest();
    }

    public static com.oddin.ots.TicketAck.TicketAckRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TicketAckRequest>
        PARSER = new com.google.protobuf.AbstractParser<TicketAckRequest>() {
      @java.lang.Override
      public TicketAckRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TicketAckRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TicketAckRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TicketAckRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.oddin.ots.TicketAck.TicketAckRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ots_TicketAckRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ots_TicketAckRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024ots/ticket_ack.proto\022\003ots\032\037google/prot" +
      "obuf/timestamp.proto\032\024ots/enum/enums.pro" +
      "to\"\250\001\n\020TicketAckRequest\022\n\n\002id\030\001 \001(\t\022-\n\tt" +
      "imestamp\030\002 \001(\0132\032.google.protobuf.Timesta" +
      "mp\0226\n\021acceptance_status\030\003 \001(\0162\033.ots.enum" +
      "s.AcceptanceStatus\022!\n\006reason\030\004 \001(\0132\021.ots" +
      ".enums.ReasonB\035\n\rcom.oddin.otsZ\014oddin.gg" +
      "/otsb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
          com.oddin.ots.Enums.getDescriptor(),
        });
    internal_static_ots_TicketAckRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ots_TicketAckRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ots_TicketAckRequest_descriptor,
        new java.lang.String[] { "Id", "Timestamp", "AcceptanceStatus", "Reason", });
    com.google.protobuf.TimestampProto.getDescriptor();
    com.oddin.ots.Enums.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
